//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopKart.web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Table
    {
        public int Id { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
    }
}
