//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopKart.web
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int Id { get; set; }
        [Required(ErrorMessage="Please enter the Name" )]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Only Alphabets allowed.")]
        [StringLength(100,ErrorMessage =" The Name must be a string with a maximum length of 100")]
        
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter the Size")]
        [Range(0, 2, ErrorMessage = "Size must be between 0 and 2")]
        public int Size { get; set; }
        [Required(ErrorMessage = "Please enter the Quantity")]
        [Range(1, 100, ErrorMessage = "Quantity must be between 1 and 100")]
        public int Quantity { get; set; }
        [Required(ErrorMessage = "Please enter the Description")]
        [RegularExpression("^[a-zA-Z0-9]*$", ErrorMessage = "Only Alphabets and Numbers allowed.")]
        [StringLength(1000, ErrorMessage = " The Description must be a string with a maximum length of 1000")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Please enter the Price")]
        public decimal Price { get; set; }
    }
}
